In [ ]:
# creating Nd array

import numpy as np #np is an alias

In [ ]:
mylist=[10,20,30,40]

#convert kist to nd array

nd_arr=np.array(mylist)

print(mylist)
print(nd_arr)

In [ ]:
# difference is functionality
# memory consumption and speed. NumPy elementas are fast and dosent take much space.

In [ ]:
print(type(mylist))
print(type(nd_arr))

In [ ]:
nd_arr # 1d,2d,3d,nd

In [ ]:
#load this image in python
img = cv2.imread(r'd:\samplepics\dd.jpg')
img

In [ ]:
type(img)

In [ ]:
# let us create some nd arrays and observe the datatypes

In [ ]:
a= np.array([1,2,3])

a.dtype

In [ ]:
b=np.array([1.1,2.2,3.3])
b.dtype

In [ ]:
c=np.array([1,'hello',5.5])
c.dtype

In [ ]:
e=np.array([True,False,True])
e.dtype

In [ ]:
# Performance Comparision Python vs Numpy
# Memory Consumption
# Speed(Fast)
#Lab1: Memory Consumption TEST
S = range(1000)



In [ ]:
D= np.arange(1000)
# how much memory is occupied by 1 integer in python

import sys
print(sys.getsizeof(5),'bytes')

print(sys.getsizeof(5)*len(S), 'bytes')

 


In [ ]:
D.itemsize  # itemsize return the size of single element

D.itemsize * D.size


In [ ]:
# itemsize  : returns size of single element in nd array
# size : return number of elements in nd array
D.size

In [ ]:
# speed test

In [ ]:
import time
SIZE= 1000000

A1 = range(SIZE)
A2 = range(SIZE)

start= time.time()

result=[x+y for x,y in zip(A1,A2)]

stop=time.time()

print('python took ',(stop-start)*1000, ' ms to complete')


L1 = np.arange(SIZE)
L2 = np.arange(SIZE)

start = time.time()
result= L1+L2
stop=time.time()

print('numpy took ',(stop-start)*1000, ' ms to complete')

time.time()

In [ ]:
#tour of nd array manipulation
# Creating 1D array

a = np.array([1,2,3,4])
 
# Creating 2D array : collection of 1d array

b = np.array ([[1,2,3],[4,5,6]])
 
# Creating 3D array : collection of 2D array

mylist=[

[[1,2,3],[4,5,6]] ,

[[7,8,9],[10,11,12]]

]


In [ ]:
c  = np.array(mylist)

In [2]:
# SLICING
import numpy as np
a = np.array([(1,2,3),(4,5,6)])
b = a[:, 2]

In [3]:
b

array([3, 6])

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[1, :]
b

array([5, 6, 7, 8])

In [7]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
b=a[[0,1,2],[0,2,0]]
b

array([1, 7, 9])

In [15]:
google = open('E:\\New folder\\google_stock_price.csv').readlines()

google

['Stock Price\n',
 '50.12\n',
 '54.1\n',
 '54.65\n',
 '52.38\n',
 '52.95\n',
 '53.9\n',
 '53.02\n',
 '50.95\n',
 '51.13\n',
 '50.07\n',
 '50.7\n',
 '49.95\n',
 '50.74\n',
 '51.1\n',
 '51.1\n',
 '52.61\n',
 '53.7\n',
 '55.69\n',
 '55.94\n',
 '56.93\n',
 '58.69\n',
 '59.62\n',
 '58.86\n',
 '59.13\n',
 '60.35\n',
 '59.86\n',
 '59.07\n',
 '63.37\n',
 '65.47\n',
 '64.74\n',
 '66.22\n',
 '67.46\n',
 '69.12\n',
 '68.47\n',
 '69.36\n',
 '68.8\n',
 '67.56\n',
 '68.63\n',
 '70.38\n',
 '70.93\n',
 '71.98\n',
 '74.51\n',
 '73.9\n',
 '70.17\n',
 '74.62\n',
 '86.13\n',
 '93.61\n',
 '90.81\n',
 '92.89\n',
 '96.55\n',
 '95.22\n',
 '97.92\n',
 '97.34\n',
 '95.74\n',
 '92.26\n',
 '84.59\n',
 '86.19\n',
 '84.27\n',
 '83.85\n',
 '91.42\n',
 '90.91\n',
 '92.34\n',
 '86.19\n',
 '86.16\n',
 '83.69\n',
 '84.62\n',
 '82.47\n',
 '83.68\n',
 '87.29\n',
 '89.61\n',
 '90.43\n',
 '90.9\n',
 '89.89\n',
 '89.61\n',
 '90.11\n',
 '88.06\n',
 '85.63\n',
 '84.91\n',
 '86.63\n',
 '85.74\n',
 '85.14\n',
 '89.26\n',
 '89.8\

In [16]:
del google[0]

In [25]:
google

[50.12,
 54.1,
 54.65,
 52.38,
 52.95,
 53.9,
 53.02,
 50.95,
 51.13,
 50.07,
 50.7,
 49.95,
 50.74,
 51.1,
 51.1,
 52.61,
 53.7,
 55.69,
 55.94,
 56.93,
 58.69,
 59.62,
 58.86,
 59.13,
 60.35,
 59.86,
 59.07,
 63.37,
 65.47,
 64.74,
 66.22,
 67.46,
 69.12,
 68.47,
 69.36,
 68.8,
 67.56,
 68.63,
 70.38,
 70.93,
 71.98,
 74.51,
 73.9,
 70.17,
 74.62,
 86.13,
 93.61,
 90.81,
 92.89,
 96.55,
 95.22,
 97.92,
 97.34,
 95.74,
 92.26,
 84.59,
 86.19,
 84.27,
 83.85,
 91.42,
 90.91,
 92.34,
 86.19,
 86.16,
 83.69,
 84.62,
 82.47,
 83.68,
 87.29,
 89.61,
 90.43,
 90.9,
 89.89,
 89.61,
 90.11,
 88.06,
 85.63,
 84.91,
 86.63,
 85.74,
 85.14,
 89.26,
 89.8,
 88.15,
 89.95,
 92.42,
 91.78,
 93.06,
 93.86,
 95.86,
 96.28,
 96.35,
 98.7,
 96.3,
 101.25,
 97.15,
 96.66,
 94.18,
 96.83,
 97.43,
 96.67,
 97.59,
 97.57,
 99.89,
 101.85,
 98.55,
 96.86,
 94.05,
 90.27,
 88.47,
 94.53,
 93.95,
 95.07,
 97.71,
 95.85,
 102.88,
 105.32,
 102.08,
 97.92,
 99.22,
 95.69,
 93.9,
 93.61,
 96.4,
 97.52,
 99.11,
 

In [19]:
google[0:5]

['50.12\n', '54.1\n', '54.65\n', '52.38\n', '52.95\n']

In [21]:
# compression
google=[float(g.strip()) for g in google]

In [22]:
google[:8]

[50.12, 54.1, 54.65, 52.38, 52.95, 53.9, 53.02, 50.95]

In [23]:
len(google)

3012

In [26]:
# let us draw some insights from this data
print('Google Stock Mean -> ',google_arr.mean())
print('Max Google Stock Value -> ',google_arr.max())
print('Min Google Stock Value -> ',google_arr.min())
print('Sum Google Stock -> ',np.sum(google_arr))
print('Google Stock Median -> ',np.median(google_arr))

NameError: name 'google_arr' is not defined

In [27]:
## Exercises 
# let us suppose we have details of 5 riders


distance =[110,190,145,178,159]

time = [2,5,3,6,7]

# objective : is to find the speed of each rider using numpy

In [29]:
np_d=np.array(distance)
np_t=np.array(time)
np_speed=np_d/np_t
np_speed

array([55.        , 38.        , 48.33333333, 29.66666667, 22.71428571])

In [30]:
arr_rand=np.array([8,8,3,7,7,0,4,2,5])
# index value >5?

In [31]:
index_gt5=np.where(arr_rand>5)
index_gt5

(array([0, 1, 3, 4], dtype=int64),)

In [32]:
# for the values fo index >5
arr_rand.take(index_gt5)

array([[8, 8, 7, 7]])

In [34]:
print(np.argmax(arr_rand)) # max value index position

0


In [35]:
print(np.argmin(arr_rand))# min value index position

5


In [36]:
arr_rand[np.argmin(arr_rand)] # min value

0

In [37]:
arr_rand[np.argmax(arr_rand)] # max value

8

In [39]:
x=np.array([1,10,5,2,8,9])
np.argsort(x)  # sorted index value 

array([0, 3, 2, 4, 5, 1], dtype=int64)

In [40]:
x[np.argsort(x)]  # sorted value

array([ 1,  2,  5,  8,  9, 10])